/**
 * Email Service for sending Tech Packs
 *
 * Uses Resend API to send tech packs via email
 */

import type { TechPack } from './techpack-generator';
import type { CollectionItem } from '../types/database';

export class EmailService {
  private resendApiKey: string;

  constructor(apiKey?: string) {
    // Use environment variable or passed key
    this.resendApiKey = apiKey || import.meta.env.VITE_RESEND_API_KEY || '';
  }

  private formatTechPackHTML(item: CollectionItem, techPack: TechPack): string {
    const formatContent = (content: any, indent: number = 0): string => {
      if (typeof content === 'string') {
        return content;
      } else if (Array.isArray(content)) {
        return content.map(item => {
          if (typeof item === 'string') {
            return `• ${item}`;
          } else if (typeof item === 'object' && item !== null) {
            return `• ${formatObjectContent(item)}`;
          }
          return '';
        }).join('<br>');
      } else if (typeof content === 'object' && content !== null) {
        return formatObjectContent(content);
      }
      return 'Not specified';
    };

    const formatObjectContent = (obj: any): string => {
      if (!obj || typeof obj !== 'object') return String(obj);

      const parts: string[] = [];
      for (const [key, value] of Object.entries(obj)) {
        if (value !== null && value !== undefined && value !== '') {
          const formattedKey = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
          const formattedValue = typeof value === 'object' ? JSON.stringify(value) : String(value);
          parts.push(`${formattedKey}: ${formattedValue}`);
        }
      }
      return parts.join(', ');
    };

    const formatSection = (title: string, section: any): string => {
      let html = `<h3 style="color: #333; margin-top: 20px; border-bottom: 1px solid #E0E0E0; padding-bottom: 5px;">${title}</h3>`;

      // Handle TechPackSection structure
      if (section && typeof section === 'object') {
        // If it has a content property (TechPackSection structure)
        if ('content' in section) {
          // Add main content if it exists
          if (section.content) {
            const contentHtml = formatContent(section.content);
            if (contentHtml && contentHtml !== 'Not specified') {
              html += `<div style="margin: 10px 0; padding-left: 20px;">${contentHtml}</div>`;
            }
          }

          // Add subsections if they exist
          if (section.subsections && Array.isArray(section.subsections)) {
            html += '<div style="margin-left: 20px;">';
            section.subsections.forEach((subsection: any) => {
              if (subsection.title) {
                html += `<h4 style="color: #555; margin-top: 15px; margin-bottom: 5px;">${subsection.title}</h4>`;
              }
              if (subsection.content) {
                const subContent = formatContent(subsection.content);
                html += `<div style="margin-left: 20px; margin-bottom: 10px; color: #666;">${subContent}</div>`;
              }
            });
            html += '</div>';
          }
        } else {
          // Fallback for direct object content
          const contentHtml = formatContent(section);
          html += `<div style="margin: 10px 0; padding-left: 20px;">${contentHtml}</div>`;
        }
      } else if (typeof section === 'string') {
        html += `<p style="margin-left: 20px;">${section}</p>`;
      }

      return html;
    };

    return `
      <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #2C3E50; border-bottom: 2px solid #3498DB; padding-bottom: 10px;">
          Tech Pack: ${item.name}
        </h1>

        <div style="background: #F8F9FA; padding: 15px; border-radius: 5px; margin: 20px 0;">
          <p><strong>SKU:</strong> ${item.sku}</p>
          <p><strong>Category:</strong> ${item.category} / ${item.subcategory}</p>
          <p><strong>Price Tier:</strong> ${item.price_tier}</p>
          <p><strong>Target Persona:</strong> ${item.target_persona}</p>
        </div>

        ${formatSection('Fabric & Materials', techPack.fabricType)}
        ${formatSection('Measurements & Sizing', techPack.measurements)}
        ${formatSection('Graphics & Branding', techPack.graphics)}
        ${formatSection('Adornments & Hardware', techPack.adornments)}
        ${formatSection('Construction Details', techPack.construction)}
        ${formatSection('Quality Control', techPack.qualityControl)}
        ${formatSection('Packaging & Presentation', techPack.packaging)}

        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #DDD; color: #666; font-size: 12px;">
          <p>Generated by TrendSync Brand Factory on ${new Date().toLocaleDateString()}</p>
        </div>
      </div>
    `;
  }

  public async sendTechPack(
    recipientEmail: string,
    item: CollectionItem,
    techPack: TechPack,
    pdfBlob?: Blob
  ): Promise<{ success: boolean; message: string }> {
    if (!this.resendApiKey) {
      return {
        success: false,
        message: 'Resend API key not configured. Please add VITE_RESEND_API_KEY to your .env file.'
      };
    }

    try {
      const htmlContent = this.formatTechPackHTML(item, techPack);

      // Prepare the request body
      const requestBody: any = {
        from: 'TrendSync Brand Factory <onboarding@resend.dev>',
        to: recipientEmail,
        subject: `Tech Pack: ${item.name} (${item.sku})`,
        html: htmlContent,
      };

      // If PDF blob is provided, convert to base64 and attach
      if (pdfBlob) {
        const arrayBuffer = await pdfBlob.arrayBuffer();
        const base64 = btoa(String.fromCharCode(...new Uint8Array(arrayBuffer)));

        requestBody.attachments = [{
          filename: `tech-pack-${item.sku}.pdf`,
          content: base64,
        }];
      }

      // Send via proxy to avoid CORS issues
      const response = await fetch('/api/resend/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${this.resendApiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        const error = await response.text();
        console.error('Resend API error:', error);
        return {
          success: false,
          message: `Failed to send email: ${error}`
        };
      }

      const result = await response.json();
      console.log('Email sent successfully:', result);

      return {
        success: true,
        message: `Tech pack sent successfully to ${recipientEmail}`
      };
    } catch (error) {
      console.error('Error sending email:', error);
      return {
        success: false,
        message: `Error sending email: ${error instanceof Error ? error.message : 'Unknown error'}`
      };
    }
  }
  /**
   * Send a login notification email to the admin.
   */
  public async sendLoginNotification(userEmail: string): Promise<void> {
    if (!this.resendApiKey) {
      console.warn('Resend API key not configured — skipping login notification email');
      return;
    }

    const now = new Date();
    const timestamp = now.toLocaleString('en-US', {
      dateStyle: 'full',
      timeStyle: 'medium',
    });

    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #2C3E50; border-bottom: 2px solid #3498DB; padding-bottom: 10px;">
          Login Alert — TrendSync Brand Factory
        </h2>
        <div style="background: #F8F9FA; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p><strong>User:</strong> ${userEmail}</p>
          <p><strong>Time:</strong> ${timestamp}</p>
          <p><strong>Browser:</strong> ${navigator.userAgent}</p>
        </div>
        <p style="color: #666; font-size: 12px; margin-top: 30px;">
          This is an automated notification from TrendSync Brand Factory.
        </p>
      </div>
    `;

    try {
      const response = await fetch('/api/resend/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${this.resendApiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          from: 'TrendSync Brand Factory <onboarding@resend.dev>',
          to: 'eimispacheco@gmail.com',
          subject: `Login Alert: ${userEmail} signed in`,
          html,
        }),
      });

      if (!response.ok) {
        const err = await response.text();
        console.error('Login notification email failed:', err);
      } else {
        console.log('Login notification email sent for', userEmail);
      }
    } catch (error) {
      console.error('Login notification email error:', error);
    }
  }
}

export const emailService = new EmailService();